### ISSUE TITLE
system hang on when uninstall 1.1.11 

### ISSUE THREAD

**Issue by liangxin1300** [mantechnology/wdrbd#11]
Hi:
     I'v installed wdrbd1.1.11; But when I uninstall it and reboot, system just hang on in "shutdown"
     please help

```
 os verstion is win 2008 r2
```

**Comment by sungeun-kim** [comment]
Hi,

Sorry, hang is not a normal situation. 

we need a Kernel Memory Dump for analyzing it.

Can you save a Kernel Memory Dump, and Send it to us?

**Comment by liangxin1300** [comment]
how to save kernel memory dump?

**Comment by sungeun-kim** [comment]
you can save a kernel memory dump by forcing to crash a machine.

a bang utility can be possible to do that.

http://www.osronline.com/article.cfm?article=153

thanks.

**Comment by sungeun-kim** [comment]
to liangxin

we verified hang while shutdown from internal test.
It will be patched WDRBD 1.2 sooner or later.

thank you for your concern.

**Comment by sungeun-kim** [comment]
to liangxin

we just release 1.2 patched this issue.

thanks again.
