### ISSUE TITLE
No drbdadm ?

### ISSUE THREAD

**Issue by sunxingwen4567** [mantechnology/wdrbd#13]
No drbdadm can be builded from the downloaded WDRBD source code, why ?

**Comment by sungeun-kim** [comment]
Hi,
drbd-utils project include drbdadm utils build.
you can check that
thanks.

**Comment by sunxingwen4567** [comment]
Thanks for your answer. 
I have already noticed that,  the directory of wdrbd-WDRBD_1.1.10_01\drbd-utils\user\v9 contains some files, such as "drbdadm_main.c". However, I cannot build these drbdadm files successfully, under the VS2013. I think that these files in the \v9 directory, are still used for Linux,  NOT for Windows.
 Can you provide the project of drbdadm, for Windows ?

**Comment by sungeun-kim** [comment]
drbd-utils (drbdadm, drbdsetup) can be built with cygwin 1.7.30.
Do you configure Cygwin build Environment? It is important to match with cygwin version.

**Comment by sunxingwen4567** [comment]
Thanks again.
I will try it with cygwin 1.7.30.
