### ISSUE TITLE
Can not exec drbdsetup

### ISSUE THREAD

**Issue by liangxin1300** [mantechnology/wdrbd#15]
Hi:

wdrbd version I use is 1.2, os is win2008 x64
When I exec "drbdadm status", I got this:
![qq 20160928161003](https://cloud.githubusercontent.com/assets/1650862/18905578/6af8c334-8596-11e6-8639-be6b16a4c90f.png)
And this is the log
[drbdService.log.txt](https://github.com/mantechnology/wdrbd/files/497422/drbdService.log.txt)
Please help!
Thanks

**Comment by sungeun-kim** [comment]
Hi, liangxin

according to next log, maybe you config M volume, but volume is offline(error code 0x80000010). 
you can check that.
and I hope that you provide us with your config file.
thanks. 

00000025 09/28/2016 15:54:42.296 [NetlinkWorkThread] WDRBD_INFO<6>[0xFFFFFA800D9A4040] done
00000026 09/28/2016 15:54:44.839 [mvolAddDevice] WDRBD_INFO<6>[0xFFFFFA800D9A5B60] VolumeExt(0xFFFFFA801E8F6190) Device(\Device\HarddiskVolume5) VolIndex(10) Active(0) MountPoint(M:)
00000027 09/28/2016 15:54:46.056 [NetlinkWorkThread] WDRBD_INFO<6>[0xFFFFFA800D989680] drbd cmd(DRBD_ADM_GET_DEVICES:31)
00000028 09/28/2016 15:54:46.056 [NetlinkWorkThread] WDRBD_INFO<6>[0xFFFFFA800D989680] done
00000029 09/28/2016 15:54:47.116 [NetlinkWorkThread] WDRBD_INFO<6>[0xFFFFFA800D9A5040] drbd cmd(DRBD_ADM_GET_RESOURCES:30)
00000030 09/28/2016 15:54:47.116 [NetlinkWorkThread] WDRBD_INFO<6>[0xFFFFFA800D9A5040] done
00000031 09/28/2016 15:54:47.148 [NetlinkWorkThread] WDRBD_INFO<6>[0xFFFFFA800D9A4B60] drbd cmd(DRBD_ADM_NEW_RESOURCE:7)
00000032 09/28/2016 15:54:47.148 [drbd_thread_start] WDRBD_INFO<6>drbd r0, r(Secondary), f(0x0) : Starting worker thread (from drbdcmd [0xFFFFFA800D9A4B60])
00000033 09/28/2016 15:54:47.148 [NetlinkWorkThread] WDRBD_INFO<6>[0xFFFFFA800D9A4B60] done
00000034 09/28/2016 15:54:47.179 [NetlinkWorkThread] WDRBD_INFO<6>[0xFFFFFA800D9A5040] drbd cmd(DRBD_ADM_NEW_MINOR:5)
00000035 09/28/2016 15:54:47.179 [mvolGetVolumeSize] WDRBD_ERRO<3>[0xFFFFFA800D9A5040] cannot get volume information, err=0x80000010
00000036 09/28/2016 15:54:47.179 [get_targetdev_volsize] WDRBD_WARN<4>[0xFFFFFA800D9A5040] get volume size error = 0x80000010

**Comment by sungeun-kim** [comment]
Hi, liangxin
we fix this issue.(WDRBD 1.3.2)

thanks.
