### ISSUE TITLE
Why WDRBD cannot be installed on Win Server 2008 32Bit ? 

### ISSUE THREAD

**Issue by sunxingwen4567** [mantechnology/wdrbd#18]
Why WDRBD cannot be installed on Win Server 2008 32Bit ?  I know that it can run on Win Server 2008 64Bit, Just because of WSK in the driver file of drbd.sys?

**Comment by sungeun-kim** [comment]
WDRBD doesn't support Win Vista Kernel. (2008 Server is vista kernel)
As you said, Vista's WSK , WFP is a crap. we don't have time to debug a Vista kernel's bug.
