### ISSUE TITLE
Why do not you make WDRBD run on Windows Server 2003, Windows XP, or even Windows2K ?

### ISSUE THREAD

**Issue by sunxingwen4567** [mantechnology/wdrbd#19]
It is required by the market that WDRBD may run on Windows Server 2003, Windows XP, or even Windows2K.

I have changed the code of drbd.sys to support it on the above OS, for example, WSK replaced with TDI. It is quite hard to do it successfully.

**Comment by sungeun-kim** [comment]
It is required by the market that WDRBD may run on Windows Server 2003
// I don't think so. market is requiring Win2008 r2 or later version. we will concentrate on this.
if you want to support 2003 on WDRBD , as you said, need to replace WSK with TDI. it is a hard work.
