### ISSUE TITLE
WDRBD Installer English UI

### ISSUE THREAD

**Issue by cbelyaev** [mantechnology/wdrbd#20]
How to run installer with English UI?

Thanks

**Comment by sungeun-kim** [comment]
The WDRBD package supports Korean and English installation.

https://github.com/mantechnology/wdrbd/releases

**Comment by cbelyaev** [comment]
Installer does support English UI, but installer bootstrapper does not.
![img0](https://cloud.githubusercontent.com/assets/16681510/26137180/f38eab84-3ad9-11e7-993f-e33e0edd4f25.png)
![img1](https://cloud.githubusercontent.com/assets/16681510/26137183/f951521a-3ad9-11e7-91db-8b8448d799d9.png)

**Comment by sungeun-kim** [comment]
ok,
We will check the problem and solve this as soon as possible.
Thank you for your reporting.

**Comment by cbelyaev** [comment]
Thanks for fixing release.
