### ISSUE TITLE
Binary packages for releases

### ISSUE THREAD

**Issue by cbelyaev** [mantechnology/wdrbd#21]
Hi

Is it possible to package releases in ZIP archives?

This will be very useful for integrating WRDBD into other products (or installers).

**Comment by sungeun-kim** [comment]
Hi,

At this time, we are not ready to deploy zip archives.
Future support will require technical review regarding driver installation, environment variables and etc...
You must use the current installation package.

thanks

**Comment by cbelyaev** [comment]
Unfortunately current installation package has non-english bootstrap UI and JRE overhead.

**Comment by sungeun-kim** [comment]
We plan to deploy a version that resolves this issue sooner or later. Please wait.

**Comment by sungeun-kim** [comment]
@cbelyaev we just release WDRBD 1.4.4, and I believe that this issue is resolved.

https://github.com/mantechnology/wdrbd/releases/tag/WDRBD_1.4.4

thanks.

**Comment by cbelyaev** [comment]
JRE overhead was not fixed.

**Comment by sungeun-kim** [comment]
longtime no see...
We do not plan to deploy zip packages in the future.
However, I hope the following links will help you.
First, you should install it as an installation package, extract the necessary files from the installation path, and manually create the zip package.

https://mantech.jira.com/wiki/spaces/WDUGE/pages/269424288/3.+Manually+install
