### ISSUE TITLE
WRDBD service/engine protocol description

### ISSUE THREAD

**Issue by cbelyaev** [mantechnology/wdrbd#22]
Hi

Is there any description of protocols used to communicate with WRDBD service (tcp port 5679) and engine (tcp port 5679)?

**Comment by sungeun-kim** [comment]
Hi, 
Basically, that part is port of drbd's netlink developed by Linbit for Windows. There is no documented part and you need to understand the implementation protocol in the source code of drbd.

thanks.

**Comment by cbelyaev** [comment]
Can you point specific source files?

**Comment by sungeun-kim** [comment]
you need to review drbd_wingenl.h, netlink.c, and Please refer to the following link we analyzed.

https://github.com/mantechnology/wdrbd/wiki/Netlink

**Comment by cbelyaev** [comment]
Thank you!
