### ISSUE TITLE
MCCS로 이중화시 문의드립니다.

### ISSUE THREAD

**Issue by Chan-Woo-Yang** [mantechnology/wdrbd#23]
가상화로 1서버(CentOS6.7), 2서버(redhat6.7)를 구성하고 MCCS구성후 페일오버 테스트시 서버1에서는 
문제없이 서버2로 스위치되는데 서버2에서 페일오버테스트시 서버1로 이동못하는 문제가 발생합니다.
도움 부탁드립니다.!
![mccs_1](https://cloud.githubusercontent.com/assets/28802312/26239189/f52edf0c-3cb6-11e7-8c20-e9acee1bfb31.JPG)

**Comment by sungeun-kim** [comment]
안녕하세요.
맨텍의 WDRBD 깃허브에 관심을 가져주셔서 감사합니다.
그런데 본 사이트는 WDRBD 와 관련한 이슈를 다루는 커뮤니티 입니다.
MCCS와 관련한 문의를 하시려면 맨텍 서비스센터로 문의를 하셔야 할 것 같습니다.

http://www.mantech.co.kr/portal/callcenter/

감사합니다.

**Comment by Chan-Woo-Yang** [comment]
넵 감사합니다.
