### ISSUE TITLE
오라클 설치후 문제발생..

### ISSUE THREAD

**Issue by Chan-Woo-Yang** [mantechnology/wdrbd#24]
![image](https://cloud.githubusercontent.com/assets/28802312/26336879/06dd6f06-3fb0-11e7-98d2-2edb28badb71.png)
![image](https://cloud.githubusercontent.com/assets/28802312/26336895/1f218160-3fb0-11e7-9b5e-b215ae363b61.png)
redhat6.7
centos6.7
oracle11R2

원인을 확인방법이 따로있을까요?..

**Comment by sungeun-kim** [comment]
남겨주신 로그만으로는 원인을 파악하는데 제한적입니다.
타겟쪽이 inconsistent 상태인것으로 봐선 리싱크가 있었고 어떤 이유에 의해서 복제 연결이 단절된 상태인것만 확인이 됩니다.
실제 물리적인 연결이 단절되었을 수도 있고 이전 단계에서 스플릿브레인이 발생하여 DRBD가 복제 연결을 끊었을 수도 있습니다.

원인분석과는 별개로 정상화를 위해선 복제 연결을 정상 회복하거나 타겟쪽 메타를 초기화 시킨 후 재동기화를 수행해야 할 것으로 보입니다.

**Comment by Chan-Woo-Yang** [comment]
감사합니다. 확인해보겠습니다.
