### ISSUE TITLE
meta-disk internal?

### ISSUE THREAD

**Issue by mailinglists35** [mantechnology/wdrbd#25]
can i have `meta-disk internal`?

I tried to do this

````
C:\Program Files\drbd\bin>drbdadm create-md r0
confused in v09_md_disk_to_cpu: expected to read 4096 bytes, actually read 16281
31152
confused in v09_md_disk_to_cpu: expected to read 4096 bytes, actually read 16281
31152
Command 'drbdmeta 0 v09 c internal create-md 1' terminated with exit code 10
````

config (protocol A):

````
resource r0 {
on linux {
device    /dev/drbd1 minor 0;
disk      /dev/zvol/temporar/wdrbd;
address   192.168.122.1:7789;
meta-disk internal;
}

on IE11Win8_1 {
device    c minor 0;
disk      c;
address   192.168.122.90:7789;
meta-disk internal;

}
````

also, can i have `meta-disk internal` with whole raw hdd? what do I write instead of `disk c` if I want entire hdd not just the partition letter C?

**Comment by sungeun-kim** [comment]
WDRBD does not support internal metadisks. It also does not support replication for OS volumes (C).
Refer to the following link for information on configuring WDRBD's metadisk.
https://mantech.jira.com/wiki/display/WDUGE/1.+Volume

thanks.

**Comment by mailinglists35** [comment]
> It also does not support replication for OS volumes (C)

is this planned or work in progress?

Thank you!

**Comment by sungeun-kim** [comment]
Fundamentally, DRBD does not support replicating on OS volumes.
Because a DRBD resource can be demoted at any time, a demotion to an OS volume during runtime will cause the machine to fail. In conclusion, DRBD is not suitable for OS volume replication.

**Comment by mailinglists35** [comment]
oh, this is total dissapointment. on linux this scenario is supported and is called '[root on drbd'](https://www.linbit.com/en/resources/technical-publications/100-storage/537-root-on-drbd/)

i was hoping to be able to have windows system volume on wdrbd, otherwise the windows implementation is **totally, completely useless** for a scenario where wdrbd was supposed to simply replicate the primary system hdd to a remote secondary location (the secondary would not be mounted, ofcourse)

if you don't support root (system volume) on drbd you should stop calling your product "windows drbd", because it's not, it's just a partial drbd implementation!

**Comment by sungeun-kim** [comment]
The root on drbd you talked about is what I read first. I have not read this in detail, but I do not understand it very well. It looks like the snapshot, not a realtime mirroring. 

What I'm talking about on a previous comment is the HA real-time mirroring perspective.

I think that 'root on drbd' is a snapshot-based backup concept. Is that right? If so, you need to understand the basic principles of DRBD.

Nevertheless, if you think WDRBD is completely useless, I hope you do not use the WDRBD anymore.

It does not matter how you evaluate WDRBD.
There are many users who are already satisfied and using it. We will improve WDRBD for them, and users like you who complain to the community like this will not be included in the category.

**Comment by mailinglists35** [comment]
> I think that 'root on drbd' is a snapshot-based backup concept. Is that right?

no. root on drbd is simply "please keep the block device on which the system volume resides in sync from primary to secondary".

it is a different thing what do I do later with the secondary (such as snapshotting). or i might simply not do anything with it and just keep it as a remote online synchronized copy, as a secondary drive (NOT as a system volume on secondary!!!)

but the main thing is: please replicate the system volume too, not just the non-system volumes. this is a feature that drbd on linux has, and a feature that wdrbd does not.

**Comment by mailinglists35** [comment]
but anyway, this discussion does not belog to 'meta-disk internal'; i will open a separate issue for it.

**Comment by sungeun-kim** [comment]
First of all,
There is no plan to add DRBD's internal metadisk functionality to WDRBD for the time being. In fact, an internal metadisk is meaningless because it is a configuration equivalent to disk partitioning. Support for file meta-disks can be meaningful.
I hope someday file metadata will be supported.

**Comment by sungeun-kim** [comment]
Here are some more.
DRBD's internal metadisk is identical to disk partitioning on Windows disk management architecture. In other words, if you partition the disk and configure the volume, that's what Linux DRBD's Internal Meta disk configuration is all about.

In other words, the function of the WDRBD's Internal meta disk is a function enhancement that the Internal-meta disk keyword can be used.

cf) I think the "meaningless" above comment was a slightly irritating expression ~ ...

thanks.
