### ISSUE TITLE
feature request: allow using the system volume block device

### ISSUE THREAD

**Issue by mailinglists35** [mantechnology/wdrbd#26]
on linux drbd can use the block device on which the operating system root filesystem resides.

on windows, wdrbd is not yet able to replicate the windows system volume hard drive.

please add the ability to replicate from windows primary system volume hdd to another secondary (w)drbd.

thank you.

**Comment by mailinglists35** [comment]
initial discussion in issue #25

**Comment by sungeun-kim** [comment]
'Root on drbd' is a way to back up mounted root filesystem by configuring initramfs, and finally use the boot architecture provided by linux. And it's doubtful whether this approach guarantees real-time mirroring by using the term snapshot on 'root on drbd].

Naturally, Windows does not have such an architecture. And even if WDRBD adds the ability to back up OS volumes, it will not support it in this way. It is necessary to examine in various ways.

**Comment by mailinglists35** [comment]
> And it's doubtful whether this approach guarantees real-time mirroring by using the term snapshot on 'root on drbd'

the snapshotting component is not provided by drbd nor mentioned in this issue.
it is really a different thing that has absolutely nothing to do with drbd.
the only thing that drbd does on linux (and is requested on this issue) is to maintain a remote synchronized copy of local blockdevice that is the underlying block device of the system volume of the primary local machine.
the remote secondary copy is not the root ("system volume") of the remote system but a regular data volume.

**Comment by mailinglists35** [comment]
> Naturally, Windows does not have such an architecture

More or less, it supports for example booting from iSCSI SAN volumes via a low level driver that loads before the NTFS filesystem driver.

The very same approach is done by lockdown-type software like DeepFreeze, Comodo Time Machine, Rollback Rx, Clean Slate and I think even Microsoft shipped it's own free alternative (these drivers load before NTFS and they provide NTFS a virtual block device on which it operates)

a similar approach can be done with the drbd driver.

**Comment by sungeun-kim** [comment]
I am grateful for your providing a lot of information.

What I would like to clarify here is whether the backup or replication of the OS volume should be added to the basic idea of DRBD, or to be provided as a separate extended function.
Alternatively, we could offer it as a separate solution. (A solution like file-level replication is also possible)

We need to prioritize replication of the DRBD's resource perspective to the intent of this github site, and may consider the ability to combine DRBD resources with local backups of redirected OS volumes.

But all of this is possible when time and resources allow it. We are very busy right now.

thanks.

**Comment by mailinglists35** [comment]
> What I would like to clarify here is whether the backup or replication of the OS volume should be added to the basic idea of DRBD, or to be provided as a separate extended function.

To be included in WDRBD and be able to pair with a Linux secondary, that would be the final goal.

Basically when I found out that there is a work in progress of drbd for windows, that was my first thought: to be able to put DRBD below NTFS system volume and have a windows machine replicated entirely in real time to a remote location.

Like I described [here,](https://github.com/mantechnology/wdrbd/issues/17#issuecomment-260597404) my ultimate wet dream is this:

````

local windows machine             .                               remote linux machine
                                  .
                                  .
  [ntfs os volume]                .                               [read-only mount of ntfs volume from read-only snapshot]
         |                        .                                                          |    
[primary drbd driver] ->->-> one way sync ->->---[remote drbd as secondary]  [read-only snapshot(s) of zvol]
         |                        .                                   |           |
 [physical storage]               .                                [zfs zvol dataset]
                                  .                                        |
                                  .                                [physical storage]
````

With above setup I can obtain near-continuous full image backup of entire Windows instalation by choosing a snapshot frequency policy on the zfs storage at a very small cost (zfs snapshots are near instant and consume only modifications since previous snapshot).

On its turn, creation of zfs snapshots for the secondary drbd virtual block device (which is a zfs zvol dataset) would allow restore to any point in time (depending on snapshot availability) by booting the local broken windows machine using a live linux os, setting up a secondary drbd device on top of the locally affected disk, setup the last good known snapshot on remote linux used as source to restore as a primary second drbd device (the zfs snapshot), and achieve a very quick restore of faulty windows to a point in time where the machine was in a good working state.

You would have ofcourse potential unsaved journal data at the time of sync but that would mean little loss as NTFS can quickly recover from this situation. Additionally if you talk to the NTFS volume manager you can ask it to prepare for a snapshot and that would trigger an announcement to all subscribers that know about NTFS shadow copies events - including MS Exchange, MS SQL Server etc - and they will sync their state to disk)

A similar goal is obtained by backup software like [Macrium Reflect](https://blog.macrium.com/techie-tuesday-macrium-changed-block-tracker-1ec3f27e7694) to create incremental full disk backups, with the difference that their backups are not stored on zfs but inside their own proprietary file format to track incremental changes, and they track changes at NTFS file system level, not at block device level. However their product is not free and the backup file format is proprietary.

**Comment by sungeun-kim** [comment]
The architecture you think is probably the topic to think of as an area of OS replication. It would not be the purpose of simply backing up. Because when the primary node is faulted, you have to restore the backup copy again.

OS replication is not as easy as it sounds. The problem of backing up or copying or restoring the OS area is an interrelated problem, and it is necessary to examine various aspects of applying DRBD to resolve the problem.

We can not solve what you are thinking. However, I think it is worth considering the support of OS backup function as a function of WDRBD.

**Comment by mailinglists35** [comment]
> The architecture you think is probably the topic to think of as an area of OS replication. It would not be the purpose of simply backing up. Because when the primary node is faulted, you have to restore the backup copy again.

Definitely! And that is why I will be using zfs snapshots to periodically save state of full disk image, so when the primary is faulted, I will have a large number of recent point in time full image snapshots available to choose to restore from.

> OS replication is not as easy as it sounds. The problem of backing up or copying or restoring the OS area is an interrelated problem, and it is necessary to examine various aspects of applying DRBD to resolve the problem.

The one and only aspect of DRBD needed is this issue: able to use OS system volume for replication.

> We can not solve what you are thinking

The only part of the diagram that this issue is about is *one-way sending _from_ local OS system volume disk _to_ remote Linux data disk*.

The other right part of the diagram (zfs storage, snapshots) is something that is not part of DRBD and therefore not expected to be a part of this github project, I've only draw it to understand the concept as a whole and I will be setting up myself.

> However, I think it is worth considering the support of OS backup function as a function of WDRBD.

Thank you, and I hope this is going to be compatible with another Linux drbd block format and protocol.
I wish you good luck and hope to not forget about this issue when you finish your current busy work! :)

**Comment by sungeun-kim** [comment]
We recently performed a technical review of OS volume replication with WDRBD. In conclusion, if we can overcome some limitations, we have confirmed that it is possible. This is an issue that has been left for a long time, so I will share it with you.

**Comment by sungeun-kim** [comment]
It seems that windrbd has implemented system volume replicating the way you want. If you are interested, check out windrbd(https://github.com/LINBIT/windrbd).
However, we will not support system volume replication in the same way as windrbd in the future.
We will implement a system volume replicating of the windows to windows model later.
