### ISSUE TITLE
Can I use C:  volume as local backing device in wdrbd?

### ISSUE THREAD

**Issue by wangmingxin** [mantechnology/wdrbd#27]
I have try it in windrbd and I don't think it  supports to use system volume as local backing device.
Could wdrbd support that?

**Comment by sungeun-kim** [comment]
hi
wdrbd does not support using a system volume as a backing device.
However, internally, we plan to support mirroring for the system volume as another type of solution, which will be sold as a commercial solution.
Thank you.

**Comment by wangmingxin** [comment]
Thank you for your reply.

**Comment by johannesthoma** [comment]
Hi, Just to let you know WinDRBD does support C: as diskless primary, however at the moment it is not possible to install a fresh Windows upon the C: device, that is why we decided to postpone official C: support. To learn how to set up a C: remote boot Windows with VirtualBox VMs you can download the guide after registering from Linbits homepage at https://www.linbit.com/tech-guide/setup-windrbd-diskless-boot/

Hope that helps,

- Johannes
