### ISSUE TITLE
ERROR when drbdadm up r0

### ISSUE THREAD

**Issue by liangxin1300** [mantechnology/wdrbd#3]
hi:
      I use driver E (volume number is 4;os: windows server 2012 x64) to sync data this time.
      my r0.res is:
[r0.res.txt](https://github.com/mantechnology/wdrbd/files/340958/r0.res.txt)
[global_common.conf.txt](https://github.com/mantechnology/wdrbd/files/340960/global_common.conf.txt)
my drbdlog is:
[drbdService.log.txt](https://github.com/mantechnology/wdrbd/files/340963/drbdService.log.txt)

When i have create-md r0, i use drbdadm up r0, then i got this error:
![1](https://cloud.githubusercontent.com/assets/1650862/16481035/c4114b8c-3edb-11e6-96dc-f0c647335447.jpg)

**Comment by sungeun-kim** [comment]
first, E: volume's minor value is 2.(c: is 0 , d: is 1)
second, according to your drbdlog, you run command-line by user privilege.
you should run command-line by admin privilege.

thanks.

**Comment by liangxin1300** [comment]
I use diskpart to get driver minor
![2](https://cloud.githubusercontent.com/assets/1650862/16482522/a543c4f8-3ee2-11e6-8750-11fe5479529a.jpg)

Is this correct?

**Comment by sungeun-kim** [comment]
wdrbd's minor value in configuration is a fixed value for WDRBD internal config. ( zero index base)
this is not related to diskpart.

**Comment by liangxin1300** [comment]
But when I use disk "I" and minor 5 (get from diskpart in my os)
WDRBD works fine, no warning or error happen

**Comment by sungeun-kim** [comment]
that is an accidental result.(maybe issue)
I hope that use a our guide.
thanks.

**Comment by liangxin1300** [comment]
I use E and minor 2 this time, got the same error
I use D and minor 1, no error happen
I use I and minor 6, no error happen

**Comment by sungeun-kim** [comment]
ok, 

first, I want a more log information.

```
drbdcon /minlog_lv svc 6
```

reproduce a your situation, and get drbdlog.

we will check that.

thank you.

**Comment by liangxin1300** [comment]
This time(use E and minor 2), I restart the drbdService
and then, drbdcon /minlog_lv svc 6
then, drbdadm create-md r0
and last, drbdadm up r0, got the same error
[drbdService.log1.txt](https://github.com/mantechnology/wdrbd/files/341138/drbdService.log1.txt)

**Comment by liangxin1300** [comment]
Thanks a lot!

**Comment by kmpak** [comment]
Hello @liangxin1300 

Is there still that problem? Only e: (minor 2).
Could you send me more information just a case, plz?

All files in c:\ry-ha\drbd\etc\drbd.d include no resource files

And need a new tested log.
1. restart the drbdService
2. drbdcon /minlog_lv svc 7
3. drbdcon /minlog_lv sys 7
4. drbdcon /minlog_lv dbg 7
5. drbdadm create-md r0
6. drbdadm up r0
7. if a error is occurred, error message or screenshot 

Thank you for your interest...

**Comment by liangxin1300** [comment]
hi @kmpak 
        Thank you for your attention.
        But I can not reproduce this situation when I reset my virtualbox snapshot.
        Thank you
