### ISSUE TITLE
How to recover the environment  which before use wdrbd?

### ISSUE THREAD

**Issue by liangxin1300** [mantechnology/wdrbd#4]
hi:
     How to recover the environment  which before use wdrbd?
     For example, I use driver D for wdrbd, and driver D become RAW disk.
     How to recover driver D when not use wdrbd? 

```
 Thanks a lot!
```

**Comment by sungeun-kim** [comment]
we will fix this issue at next patch (WDRBD 1.2)
at current version, reboot required.

I appreciate your concern.

thank you

**Comment by kmpak** [comment]
@liangxin1300 
I think, it works right, if in running wdrbd.
Because wdrbd should protect the data from the various cases basically.

But you want to access D:, I recommend below step.
1. Delete or rename that resource file include d:, so that res's file will be disabled.
2. And reboot

Thank you

**Comment by kmpak** [comment]
@liangxin1300 
Is answer enough?

I also concern for your need, and I want to help you.

**Comment by liangxin1300** [comment]
@kmpak 
The answer is enough well
Thanks a lot!
