### ISSUE TITLE
Is this config file correct if I want  to use duplex  mirror？

### ISSUE THREAD

**Issue by liangxin1300** [mantechnology/wdrbd#5]
HI dear all: 
    What should I write the config file if I want to use duplex mirror?
    For example:
    node1: D   ---->  node2: D
    node1: E   <----  node2: E

[r0.res.txt](https://github.com/mantechnology/wdrbd/files/351199/r0.res.txt)
[r1.res.txt](https://github.com/mantechnology/wdrbd/files/351200/r1.res.txt)

```
Is this correct for r0 and r1  share the same IP and with different ports(7789 for r0 and 7790 for r1)?
Or, use different IP between r0 and r1 is better?
```

**Comment by sungeun-kim** [comment]
Hi, liangxin
basically, your config is right. (same IP and different ports)
But one thing is , node2(win8-b)'s meta volume letter may be 'n' in r0 config.
currently, your config is 'm'

thanks.

**Comment by liangxin1300** [comment]
Thank you
