### ISSUE TITLE
Both nodes' status are Outdated after recover from splitBrain

### ISSUE THREAD

**Issue by liangxin1300** [mantechnology/wdrbd#6]
hi all:
     1: both nodes' status are UpToDate;
     2: shutdown node2, then primary on node1 and  write data on node1;
     3: shutdown node1, then start node2, then primary on node2 and write some data on node2;
     4: start node1, and this time, both nodes' status are "StandAlone";
     5: make sure both nodes' role is "Secondary";
     6: on node1, run command "drbdadm connect --discard-my-data r0";
     7: on node2, run "drbdadm connect r0";
     8: I found both nodes' disk status are "Outdated"

[drbdService_node1.txt](https://github.com/mantechnology/wdrbd/files/353992/drbdService_node1.txt)
[drbdService_node2.txt](https://github.com/mantechnology/wdrbd/files/353996/drbdService_node2.txt)

**Comment by reinhardvz** [comment]
this Outdated issue is maybe known issue. (after resync, disk go to outdated)

this is drbd9's original bug. we will fix it at next version.

at this situation, you can make one node to UptoDate by "drbdadm primary --force <res>" .
until next patch, I hope that temporarily this way is used.

thank you.

**Comment by sungeun-kim** [comment]
We believe that this issue is fixed in 1.1.8
you can check this.
thanks.
