### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by liangxin1300** [mantechnology/wdrbd#7]
Hi all:
       I see 1.1.3 is released. Does have any ChangLog or ReleaseNotes?

```
   Thanks for your attention!
```

**Comment by sungeun-kim** [comment]
Hi, liangxin

1.1.3 is a temporary version for internal test.

It's not stable yet. don't use it.

thank you for your concern.

**Comment by sungeun-kim** [comment]
we just release 1.1.8 

https://github.com/mantechnology/wdrbd/wiki/Release-Note

thanks.
