### ISSUE TITLE
Fast initially sync?

### ISSUE THREAD

**Issue by liangxin1300** [mantechnology/wdrbd#8]
Hi all:
       Currently, how to make wdrbd sync fast at first time?
       Thanks!

**Comment by sungeun-kim** [comment]
Hi, 
we changed the wdrbd's default option - c-plan-ahead is zero.
and then you should set resync-rate. (100M is good enough for 1G network)

we recommend that install 1.1.10 from downloads page.

thanks.

**Comment by liangxin1300** [comment]
@sungeun-kim  
Do you mean I need add "resync-rate 100M;" in config file;
and then add option "c-plan-ahead" when run the init sync command?

**Comment by sungeun-kim** [comment]
correct. you need to add "resync-rate 100M;"

and don't need to add c-plan-ahead option. (already be set by default option.)
